In [136]:
import numpy as np

np_array_one = np.ones(5)

np_array1 = np.full((5, 5), np_array_one)
np_array2 = np.full((5, 5), 5)

np_array3 = np_array1 + np_array2
np_array4 = np_array1 + np_array2

for count in range(5):
    np_array4[count][count] = (np_array1[0][0] + np_array2[0][0]) ** 2
    np_array4[count][len(range(5 - 1)) - count] = (np_array1[0][0] + np_array2[0][0]) ** 2

i = 2
np_array4[i][i] = (np_array1[i][i] + np_array2[i][i]) ** 2

print("[ 출력결과 ]")
print(np_array3)
print()
print("[ 출력결과 ]")
print(np_array4)

[ 출력결과 ]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]

[ 출력결과 ]
[[36.  6.  6.  6. 36.]
 [ 6. 36.  6. 36.  6.]
 [ 6.  6. 36.  6.  6.]
 [ 6. 36.  6. 36.  6.]
 [36.  6.  6.  6. 36.]]


In [ ]:
[ 출력결과 ]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]

[ 출력결과 ]
[[36.  6.  6.  6. 36.]
 [ 6. 36.  6. 36.  6.]
 [ 6.  6. 36.  6.  6.]
 [ 6. 36.  6. 36.  6.]
 [36.  6.  6.  6. 36.]]